const INCREMENT = 'INCREMENT';
const INCREMENT_SUCCESS = 'INCREMENT_SUCCESS';
const DECREMENT = 'DECREMENT';
const DECREMENT_SUCCESS = 'DECREMENT_SUCCESS';

export {
    INCREMENT,
    INCREMENT_SUCCESS,
    DECREMENT,
    DECREMENT_SUCCESS
}