const INCREMENT = 'INCREMENT';
const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
const INCREMENT_SUCCESS = 'INCREMENT_SUCCESS';
const INCREMENT_ASYNC_SUCCESS = 'INCREMENT_ASYNC_SUCCESS';
const DECREMENT = 'DECREMENT';
const DECREMENT_ASYNC = 'DECREMENT_ASYNC';
const DECREMENT_SUCCESS = 'DECREMENT_SUCCESS';
const DECREMENT_ASYNC_SUCCESS = 'DECREMENT_ASYNC_SUCCESS';

export {
    INCREMENT,
    INCREMENT_ASYNC,
    INCREMENT_SUCCESS,
    INCREMENT_ASYNC_SUCCESS,
    DECREMENT,
    DECREMENT_ASYNC,
    DECREMENT_SUCCESS,
    DECREMENT_ASYNC_SUCCESS
};
